---
ID: "c2a0c38f-d68b-4f7e-911d-33a3ca3db5f5"
Parent: "38533092-c1b4-42d1-945f-9f48aba9b831"
Template: "e43add4c-eea3-47a1-8271-e64a9fd0a209"
Path: "/sitecore/content/energy-utilities/gridwell/Home/Services"
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{5704DC6A-EB4D-4306-B7AA-9943110491BA}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250919T211141Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7024bf14-e272-4769-a106-d8b7b6763ff9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250919T211141Z
    - ID: "fec597dd-3b38-4232-a472-83d725de4d8e"
      Hint: Title
      Value: Services
