---
ID: "2e5e674b-0b8f-4e08-9aaf-13351e586d9b"
Parent: "341c050b-f031-4bd4-a78d-7a43def63beb"
Template: "341c050b-f031-4bd4-a78d-7a43def63beb"
Path: "/sitecore/templates/Project/transport-logistics/Datasource Templates/Services/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250808T160749Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b2583d28-35d6-46b5-954e-7bfaca974b64"
    - ID: "b14cc411-a06d-4076-bc45-6f60e7e85991"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250808T160754Z
