---
ID: "0aa01fe3-77e7-409a-bfe3-d8924fb9b021"
Parent: "159e37cf-25a0-4eaf-903a-9034e4b989d8"
Template: "159e37cf-25a0-4eaf-903a-9034e4b989d8"
Path: "/sitecore/templates/Project/energy-utilities/Author/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250922T160859Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "923b479f-8966-4bd9-aaed-8873d8e7536c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250922T160903Z
    - ID: "db8b5ff9-f71b-41c0-8bf5-7de11b5af232"
      Hint: Name
      Value: $name
