---
ID: "77a91927-6863-43d6-b339-ee670e9894de"
Parent: "8e88e14f-16cf-40e8-b30a-233ef25c725c"
Template: "ea5ef5dc-7348-48b2-bfa5-c4e3300e14cb"
Path: "/sitecore/content/transport-logistics/nationalpost/Home/personal/Services"
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{76B64728-3246-4335-AF48-E2C732A74944}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250807T150044Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "762d4fec-aae0-4bfc-ad90-45471f1b9fbd"
      Hint: Title
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bf3dedf3-8f64-4973-a26b-a74e2f72b4bb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250807T150044Z
