---
ID: "035b3ec0-6164-4e86-a71b-335ee66302fa"
Parent: "c5db88b0-5619-4509-8b55-ba0c409a8afb"
Template: "c5db88b0-5619-4509-8b55-ba0c409a8afb"
Path: "/sitecore/templates/Project/travel-hospitality/Datasource Templates/SearchBanner/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250730T193340Z
    - ID: "2ee43eae-e00e-4b95-ba8a-6dc4866b8be7"
      Hint: customer_key
      Value: "202092313-225191452"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "87818e76-db51-4ec7-9dd6-09d55be8454f"
      Hint: api_key
      Value: "01-8fa0d33b-6fefe6b976b8efc209b6d71333d76141d2f549be"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63288b10-9dd1-457b-8b85-bababf7f6946"
    - ID: "8ee4c944-0ea3-439d-bddd-fe50f993ab4e"
      Hint: search_env
      Value: prod
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250730T193356Z
    - ID: "f9e54dd4-353d-4fc5-bb52-d28f8c092373"
      Hint: search_source
      Value: 1146218|1145395
