---
ID: "5b1122b1-f3a1-46f5-be68-5223c33fad23"
Parent: "c09a25bd-2f02-4596-bf97-b660a8ba1512"
Template: "c09a25bd-2f02-4596-bf97-b660a8ba1512"
Path: "/sitecore/templates/Project/travel-hospitality/Holiday Type/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250730T160116Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "6a38557e-3b0c-428d-ae5c-05bd58f1bb58"
      Hint: Name
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aafe2b8f-a017-4979-a8d5-b0b1b4675695"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250730T160119Z
