---
ID: "9ebf780a-d88b-4092-9fd0-ce193220b8d1"
Parent: "fd466fad-c06c-4532-8c8f-ffdc218f35f0"
Template: "fd466fad-c06c-4532-8c8f-ffdc218f35f0"
Path: /sitecore/templates/Project/healthcare/Components/HeroSectionParameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250904T175410Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\brad.thomsen@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\brad.thomsen@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9ae1f8ea-ad5c-48a9-ba3c-5a8711928260"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\brad.thomsen@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250904T175410Z
