---
ID: "f8ee6817-babe-455b-9d19-36198ae39062"
Parent: "68c7edf6-35ad-449a-8aa1-6c185c6808bf"
Template: "68c7edf6-35ad-449a-8aa1-6c185c6808bf"
Path: "/sitecore/templates/Project/travel-hospitality/Class/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250730T171051Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a8aaa7ed-453f-4562-b83d-dcae869f8381"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250730T171102Z
    - ID: "e2bb32aa-fe77-4957-9362-0c3249425678"
      Hint: Title
      Value: $name
